[package]
name = "embedded"
version = "0.1.0"
edition = "2024"

[dependencies]
#embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "defmt"] }
#embassy-futures = "0.1.1"
#embassy-net = { version = "0.6.0", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "proto-ipv6"] }
#embassy-stm32 = { version = "0.2.0", features = ["defmt", "stm32h563zi", "memory-x", "time-driver-any", "exti", "unstable-pac", "low-power"] }
#embassy-sync = { version = "0.6.2", features = ["defmt"] }
#embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
#cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
#cortex-m-rt = "0.7.5"
#embedded-hal = "0.2.6"
#embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
#embedded-hal-async = { version = "1.0" }
#embedded-io-async = { version = "0.6.1" }
#embedded-nal-async = "0.8.0"
#panic-probe = { version = "0.3", features = ["print-defmt"] }
#heapless = { version = "0.8", default-features = false }
#rand_core = "0.9.1"
#critical-section = "1.1"
#micromath = "2.0.0"
#stm32-fmc = "0.4.0"
#embedded-storage = "0.3.1"
#static_cell = "2"
#defmt = "1.0.1"
#defmt-rtt = "1.0.0"
log = "0.4.27"
embassy-stm32 = { version = "0.2.0", features = ["defmt", "stm32h563zi", "memory-x", "time-driver-any", "exti", "unstable-pac", "low-power"] }
embassy-sync = { version = "0.6.2", features = ["defmt"] }
embassy-executor = { version = "0.7.0", features = ["arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4.0", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-net = { version = "0.6.0", features = ["defmt", "tcp", "dhcpv4", "medium-ethernet", "proto-ipv6"] }
embassy-usb = { version = "0.4.0", features = ["defmt"] }
embassy-futures = { version = "0.1.0" }

defmt = "0.3"
defmt-rtt = "0.4"

cortex-m = { version = "0.7.6", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.6"
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = { version = "1.0" }
embedded-io-async = { version = "0.6.1" }
embedded-nal-async = "0.8.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
heapless = { version = "0.8", default-features = false }
rand_core = "0.6.3"
critical-section = "1.1"
micromath = "2.0.0"
stm32-fmc = "0.3.0"
embedded-storage = "0.3.1"
static_cell = "2"
emballoc = "0.3.0"
