[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.10.2"
rust-embed = "8.7.0"
tokio = { version = "1.43.0", features = ["macros", "rt-multi-thread"] }
actix-cors = "0.7.0"
mime_guess = "2.0.5"
env_logger = "0.11.6"
log = "0.4.27"
